package com.guokrspace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TIME_RECORD_ENTITY.
 */
public class TimeRecordEntity {

    private Long id;
    private String cardid;
    private String machine;
    private Float temperature;
    private String healthstate;
    private Long createtime;
    private String fbody;
    private String fext;

    public TimeRecordEntity() {
    }

    public TimeRecordEntity(Long id) {
        this.id = id;
    }

    public TimeRecordEntity(Long id, String cardid, String machine, Float temperature, String healthstate, Long createtime, String fbody, String fext) {
        this.id = id;
        this.cardid = cardid;
        this.machine = machine;
        this.temperature = temperature;
        this.healthstate = healthstate;
        this.createtime = createtime;
        this.fbody = fbody;
        this.fext = fext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCardid() {
        return cardid;
    }

    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    public String getMachine() {
        return machine;
    }

    public void setMachine(String machine) {
        this.machine = machine;
    }

    public Float getTemperature() {
        return temperature;
    }

    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    public String getHealthstate() {
        return healthstate;
    }

    public void setHealthstate(String healthstate) {
        this.healthstate = healthstate;
    }

    public Long getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    public String getFbody() {
        return fbody;
    }

    public void setFbody(String fbody) {
        this.fbody = fbody;
    }

    public String getFext() {
        return fext;
    }

    public void setFext(String fext) {
        this.fext = fext;
    }

}
