package com.cytx.timecard.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARENTS_ENTITY.
 */
public class ParentsEntity {

    private Long id;
    private String relation;
    private String avatar;
    /** Not-null value. */
    private String studentid;

    public ParentsEntity() {
    }

    public ParentsEntity(Long id) {
        this.id = id;
    }

    public ParentsEntity(Long id, String relation, String avatar, String studentid) {
        this.id = id;
        this.relation = relation;
        this.avatar = avatar;
        this.studentid = studentid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRelation() {
        return relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /** Not-null value. */
    public String getStudentid() {
        return studentid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

}
