package com.cytx.timecard.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_ENTITY.
 */
public class StudentEntity {

    private String studentid;
    private String pid;
    private String cnnname;
    private String schoolname;
    private String avatar;
    private String classname;

    public StudentEntity() {
    }

    public StudentEntity(String studentid, String pid, String cnnname, String schoolname, String avatar, String classname) {
        this.studentid = studentid;
        this.pid = pid;
        this.cnnname = cnnname;
        this.schoolname = schoolname;
        this.avatar = avatar;
        this.classname = classname;
    }

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getCnnname() {
        return cnnname;
    }

    public void setCnnname(String cnnname) {
        this.cnnname = cnnname;
    }

    public String getSchoolname() {
        return schoolname;
    }

    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname = classname;
    }

}
